"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$python\
$rust\
$golang\
$nodejs\
$docker_context\
$time\
$line_break\
$character"""

add_newline = true

[username]
style_user = "bold #bb9af7"
style_root = "bold #f7768e"
format = "[$user]($style) "
show_always = false

[hostname]
ssh_only = false
format = "at [$hostname](bold #7dcfff) in "
disabled = true

[directory]
style = "bold #7aa2f7"
format = "[  $path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Desktop" = " "

[git_branch]
symbol = " "
style = "bold #9ece6a"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #e0af68"
format = '([$all_status$ahead_behind]($style) )'

[c]
symbol = " "
style = "bold #2ac3de"
format = 'via [$symbol($version)]($style) '

[python]
symbol = " "
style = "bold #e0af68"
format = 'via [$symbol($version)]($style) '

[rust]
symbol = " "
style = "bold #f7768e"
format = 'via [$symbol($version)]($style) '

[golang]
symbol = " "
style = "bold #7dcfff"
format = 'via [$symbol($version)]($style) '

[nodejs]
symbol = " "
style = "bold #9ece6a"
format = 'via [$symbol($version)]($style) '

[docker_context]
symbol = " "
style = "bold #bb9af7"
format = 'via [$symbol$context]($style) '

[time]
disabled = false
time_format = "%R"
style = "bold #565f89"
format = 'at [$time]($style) '

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"
vimcmd_symbol = "[❮](bold #bb9af7)"
